name: Deploy to Test Server
on:
  push:
    tags:
      - 'test/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: test logging
        run: |
          echo "Logging For Test"
      
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Build Project With Gradle
      #   run: |
      #     ./gradlew bootJar

      # - name: Set Env Variables In Test Server
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source script/set_env.sh'
          
      # - name: Deploy Jar
      #   run: |
      #     scp build/libs/demo-0.0.1-SNAPSHOT.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }}:script/jobcat_app.jar
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Kill Old Program
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source script/kill_old_process.sh'

      # - name: Run New Program
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source script/run_new_process.sh'
