name: Deploy to Test Server
on:
  push:
    tags:
      - 'test/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Project With Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean bootJar

      - name: Deploy Jar
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_IP_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: build/libs/demo-0.0.1-SNAPSHOT.jar
          target: script

      - name: Run New Program
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_IP_ADDRESS }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            source script/kill_old_process.sh
            source script/set_env.sh
            source script/run_new_process.sh
