name: Deploy to Test Server
on:
  push:
    tags:
      - 'test/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Build Project With Gradle
      #   run: |
      #     ./gradlew bootJar

      # - name: Set Env Variables In Test Server
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'cat {{ secrets.ENV_VAR }} > .env'
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source .env'
          
      # - name: Deploy Jar
      #   run: |
      #     scp build/libs/demo-0.0.1-SNAPSHOT.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }}:/jobcat_app.jar
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Kill Old Program
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} '  '

      # - name: Run New Program
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'java --jar jobcat_app.jar'
