name: Deploy to Test Server
on:
  push:
    tags:
      - 'test/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v2

      # - name: Set up JDK 17
      #   uses: actions/setup-java@v3
      #   with:
      #     java-version: '17'
      #     distribution: 'temurin'

      # - name: Build Project With Gradle
      #   run: |
      #     chmod +x ./gradlew
      #     ./gradlew clean bootJar

      - name: Set Env Variables In Test Server
        run: |
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source script/set_env.sh'
          ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} "echo 'success setting env'"
          
      # - name: Deploy Jar
      #   run: |
      #     scp build/libs/demo-0.0.1-SNAPSHOT.jar ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }}:script/jobcat_app.jar
      #   env:
      #     SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      # - name: Kill Old Program
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source script/kill_old_process.sh'

      # - name: Run New Program
      #   run: |
      #     ssh ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_IP_ADDRESS }} 'source script/run_new_process.sh'
